image: java:8

stages:
  - build
  - test

build:
  stage: build
  script: ./petproject/mvn -f .petproject/pom.xml mvn clean install


test:
  stage: test
  script: ./petproject/mvn -f .petproject/pom.xml mvn clean test
